### ISSUE TITLE
Unknown database issue 

### ISSUE THREAD

**Issue by vikas-nichi** [jesseskinner/codingwithjesse.com#1]
db log when given custom port for mysql eg: 5600

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle codingwithjesse.com@1.0.0~presetup: codingwithjesse.com@1.0.0
6 info lifecycle codingwithjesse.com@1.0.0~setup: codingwithjesse.com@1.0.0
7 verbose lifecycle codingwithjesse.com@1.0.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle codingwithjesse.com@1.0.0~setup: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Admin\Desktop\nichi-in\new_tech\svelte\codingwithjesse_com\node_modules\.bin;C:\Program Files\PowerShell\7;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\MySQL\MySQL Server 5.5\bin;C:\php-7.4.3;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\Admin\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Admin\AppData\Local\Programs\Python\Python38\;C:\Users\Admin\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Admin\AppData\Local\Programs\Python\Python37\;C:\Program Files\Java\jdk1.8.0_102\bin;C:\Program Files\Java\jdk1.8.0_102\lib;C:\MyApache\apache-tomcat-8.0.17\bin;C:\MyApache\apache-tomcat-8.0.17\lib;C:\wildfly-8.2.0.Final\bin;C:\Users\Admin\AppData\Roaming\Composer\vendor\bin;C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Admin\AppData\Roaming\npm;C:\Users\Admin\AppData\Local\GitHubDesktop\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\src\flutter\bin;C:\Users\Admin\AppData\Local\Android\Sdk\tools\emulator.exe;C:\tools\dart-sdk\bin;C:\Users\Admin\AppData\Roaming\Pub\Cache\bin
9 verbose lifecycle codingwithjesse.com@1.0.0~setup: CWD: C:\Users\Admin\Desktop\nichi-in\new_tech\svelte\codingwithjesse_com
10 silly lifecycle codingwithjesse.com@1.0.0~setup: Args: [ '/d /s /c', 'node app/setup.js' ]
11 silly lifecycle codingwithjesse.com@1.0.0~setup: Returned: code: 1  signal: null
12 info lifecycle codingwithjesse.com@1.0.0~setup: Failed to exec setup script
13 verbose stack Error: codingwithjesse.com@1.0.0 setup: `node app/setup.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid codingwithjesse.com@1.0.0
15 verbose cwd C:\Users\Admin\Desktop\nichi-in\new_tech\svelte\codingwithjesse_com
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error codingwithjesse.com@1.0.0 setup: `node app/setup.js`
22 error Exit status 1
23 error Failed at the codingwithjesse.com@1.0.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
[2020-04-22T10_52_00_515Z-debug.log.txt](https://github.com/jesseskinner/codingwithjesse.com/files/4515638/2020-04-22T10_52_00_515Z-debug.log.txt)
`

**Comment by jesseskinner** [comment]
As happy as I am for you to read the code and learn from it, I never intended others to use this, so it's out of scope of this project to get it working for all platforms and configurations. I'm going to close the issue. Sorry about that.
